export const ContactData = [
    {
      'id': 1,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 2,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 3,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 4,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 5,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 6,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 7,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 8,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 9,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 10,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 11,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 12,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 13,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 14,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 15,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 16,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    },
    {
      'id': 17,
      'contactType': 'Customer',
      'subContactType': 'Consignment Contact',
      'bname': 'Business Name',
      'jobTitle': 'Job Title',
      'fname': 'Zahidul',
      'lname': 'Islam',
      'ltype': '100 PC Street',
      'locationName': '100 PC Street',
      'address': '100 PC Street',
      'city': 'DHAKA',
      'zipCode': 1215,
      'country': 'Bangladesh',
      'phone': '+32 (818) 580-3557',
      'mobile':'01710112233',
      'email': 'abc@gmail.com',
      'description': 'Head Office'
    }
  ]
  