export const UserData = [
    {
        'id': 1,
        'fname': 'Zahidul',
        'lname': 'Islam',
        'uname': 'ZI-101',
        'description': 500,
        'ltype': 'DHAKA',
        'lgroup': 'DHAKA',
        'mobile':'01710112233',
        'email': 'abc@gmail.com',
        'uid': 'UI-101',
        'password': '1234',
        'ugroupid': '1'
    },
    // {id: 2, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 3, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 4, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 5, name: 'Purchasing', description: 10.811, action: 'B'},
    // {id: 6, name: 'Admins', description: 1.0079, action: 'H'},
    // {id: 7, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 8, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 9, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 10, name: 'Purchasing', description: 10.811, action: 'B'},
    // {id: 11, name: 'Admins', description: 1.0079, action: 'H'},
    // {id: 12, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 13, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 14, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 15, name: 'Purchasing', description: 10.811, action: 'B'},
    // {id: 16, name: 'Admins', description: 1.0079, action: 'H'},
    // {id: 17, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 18, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 19, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 20, name: 'Purchasing', description: 10.811, action: 'B'},
    // {id: 21, name: 'Admins', description: 1.0079, action: 'H'},
    // {id: 22, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 23, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 24, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 25, name: 'Purchasing', description: 10.811, action: 'B'},
    // {id: 26, name: 'Admins', description: 1.0079, action: 'H'},
    // {id: 27, name: 'Acountants', description: 4.0026, action: 'He'},
    // {id: 28, name: 'Receiving', description: 6.941, action: 'Li'},
    // {id: 29, name: 'Shipping', description: 9.0122, action: 'Be'},
    // {id: 30, name: 'Purchasing', description: 10.811, action: 'B'}  
]
  