export const ALL_IN_ONE_TABLE_DEMO_DATA = [
    {
      'id': 1,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 2,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 3,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 4,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 5,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 6,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 7,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 8,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 9,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    },
    {
      'id': 10,
      'locgroup': 'LA ',
      'location': 'Head Office',
      'locationType': 'Head Office',
      'name': 'Business Name',
      'jobtitle': 'Contact Authority',
      'firstName': 'Short',
      'lastName': 'Lowe',
      'address': '548 Cypress Avenue',
      'zipcode': 5943,
      'city': 'Temperanceville',
      'country': 'Bangladesh',
      'phoneNumber': '+11 (977) 574-3636',
      'mobileNumber':'01710112233',
      'mail': 'abc@gmail.com'
    }
  ]
  